// desktop/src/App.vue
<script setup lang="ts">
</script>

<template>
  <div>
    <h1>@idrinth-api-bench/api-bench</h1>
    <img src="./assets/iab.svg" class="logo" alt="logo" />
  </div>
</template>

<style scoped>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #42b883aa);
  }
</style>

// history-website/src/App.svelte
<script lang="ts" context="module">
  import logo from '@idrinth-api-bench/assets/iab.svg';
  import t from './lib/t.js';
</script>

<main>
  <header>
    <img src={logo} class="logo" alt="Logo" />
  </header>
  <h1>{t('overview.title',)}</h1>

  <div class="card">
  </div>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
</style>
